name: Kartoza Biodiversity Information Management System
description: A platform for storing and sharing biodiversity related data.
version: 1
category: GIS
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/django-bims
